
name: Sync To Notion

on: [push, ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository.
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: |
            python3 --version
            python3 -m pip install -U pip
            pip install --no-cache-dir --force-reinstall git+https://github.com/sciunto-org/python-bibtexparser@main

      - name: Sync to notion
        run: python sync.py
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          DATABASE_IDENTIFIER: ${{secrets.DATABASE_IDENTIFIER}}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
